using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SpeedySpots.Business.Helpers
{
    public static class Countries
    {
        public static List<KeyValuePair<string, string>> GetCountries()
        {
            List<KeyValuePair<string, string>> countries = new List<KeyValuePair<string, string>>();
            countries.Add(new KeyValuePair<string,string>("United States", "United States"));
            countries.Add(new KeyValuePair<string,string>("Algeria", "Algeria"));
            countries.Add(new KeyValuePair<string,string>("Alond Islands", "Alond Islands"));
            countries.Add(new KeyValuePair<string,string>("American Samoa", "American Samoa"));
            countries.Add(new KeyValuePair<string,string>("Andorra", "Andorra"));
            countries.Add(new KeyValuePair<string,string>("Angola", "Angola"));
            countries.Add(new KeyValuePair<string,string>("Anguilla", "Anguilla"));
            countries.Add(new KeyValuePair<string,string>("Antarctica", "Antarctica"));
            countries.Add(new KeyValuePair<string,string>("Antigua and Barbuda", "Antigua and Barbuda"));
            countries.Add(new KeyValuePair<string,string>("Argentina", "Argentina"));
            countries.Add(new KeyValuePair<string,string>("Aruba", "Aruba"));
            countries.Add(new KeyValuePair<string,string>("Asia/Pacific Region", "Asia/Pacific Region"));
            countries.Add(new KeyValuePair<string,string>("Australia", "Australia"));
            countries.Add(new KeyValuePair<string,string>("Austria", "Austria"));
            countries.Add(new KeyValuePair<string,string>("Bahamas", "Bahamas"));
            countries.Add(new KeyValuePair<string,string>("Bahrain", "Bahrain"));
            countries.Add(new KeyValuePair<string,string>("Bangladesh", "Bangladesh"));
            countries.Add(new KeyValuePair<string,string>("Barbados", "Barbados"));
            countries.Add(new KeyValuePair<string,string>("Belgium", "Belgium"));
            countries.Add(new KeyValuePair<string,string>("Belize", "Belize"));
            countries.Add(new KeyValuePair<string,string>("Benin", "Benin"));
            countries.Add(new KeyValuePair<string,string>("Bermuda", "Bermuda"));
            countries.Add(new KeyValuePair<string,string>("Bhutan", "Bhutan"));
            countries.Add(new KeyValuePair<string,string>("Bolivia", "Bolivia"));
            countries.Add(new KeyValuePair<string,string>("Bosnia and Herzegovina", "Bosnia and Herzegovina"));
            countries.Add(new KeyValuePair<string,string>("Botswana", "Botswana"));
            countries.Add(new KeyValuePair<string,string>("Bouvet Island", "Bouvet Island"));
            countries.Add(new KeyValuePair<string,string>("Brazil", "Brazil"));
            countries.Add(new KeyValuePair<string,string>("British Indian Ocean Territory", "British Indian Ocean Territory"));
            countries.Add(new KeyValuePair<string,string>("Brunei Darussalam", "Brunei Darussalam"));
            countries.Add(new KeyValuePair<string,string>("Bulgaria", "Bulgaria"));
            countries.Add(new KeyValuePair<string,string>("Burkina Faso", "Burkina Faso"));
            countries.Add(new KeyValuePair<string,string>("Burundi", "Burundi"));
            countries.Add(new KeyValuePair<string,string>("Cameroon", "Cameroon"));
            countries.Add(new KeyValuePair<string,string>("Canada", "Canada"));
            countries.Add(new KeyValuePair<string,string>("Cape Verde", "Cape Verde"));
            countries.Add(new KeyValuePair<string,string>("Cayman Islands", "Cayman Islands"));
            countries.Add(new KeyValuePair<string,string>("Central African Republic", "Central African Republic"));
            countries.Add(new KeyValuePair<string,string>("Chad", "Chad"));
            countries.Add(new KeyValuePair<string,string>("Chile", "Chile"));
            countries.Add(new KeyValuePair<string,string>("Christmas Island", "Christmas Island"));
            countries.Add(new KeyValuePair<string,string>("Cocos (Keeling) Islands", "Cocos (Keeling) Islands"));
            countries.Add(new KeyValuePair<string,string>("Colombia", "Colombia"));
            countries.Add(new KeyValuePair<string,string>("Comoros", "Comoros"));
            countries.Add(new KeyValuePair<string,string>("Congo", "Congo"));
            countries.Add(new KeyValuePair<string,string>("Congo, The Democratic Republic of the", "Congo, The Democratic Republic of the"));
            countries.Add(new KeyValuePair<string,string>("Cook Islands", "Cook Islands"));
            countries.Add(new KeyValuePair<string,string>("Costa Rica", "Costa Rica"));
            countries.Add(new KeyValuePair<string,string>("Cote d'Ivoire", "Cote d'Ivoire"));
            countries.Add(new KeyValuePair<string,string>("Croatia", "Croatia"));
            countries.Add(new KeyValuePair<string,string>("Cyprus", "Cyprus"));
            countries.Add(new KeyValuePair<string,string>("Czech Republic", "Czech Republic"));
            countries.Add(new KeyValuePair<string,string>("Denmark", "Denmark"));
            countries.Add(new KeyValuePair<string,string>("Djibouti", "Djibouti"));
            countries.Add(new KeyValuePair<string,string>("Dominica", "Dominica"));
            countries.Add(new KeyValuePair<string,string>("Dominican Republic", "Dominican Republic"));
            countries.Add(new KeyValuePair<string,string>("Ecuador", "Ecuador"));
            countries.Add(new KeyValuePair<string,string>("Egypt", "Egypt"));
            countries.Add(new KeyValuePair<string,string>("El Salvador", "El Salvador"));
            countries.Add(new KeyValuePair<string,string>("Equatorial Guinea", "Equatorial Guinea"));
            countries.Add(new KeyValuePair<string,string>("Eritrea", "Eritrea"));
            countries.Add(new KeyValuePair<string,string>("Estonia", "Estonia"));
            countries.Add(new KeyValuePair<string,string>("Ethiopia", "Ethiopia"));
            countries.Add(new KeyValuePair<string,string>("Europe", "Europe"));
            countries.Add(new KeyValuePair<string,string>("Falkland Islands (Malvinas)", "Falkland Islands (Malvinas)"));
            countries.Add(new KeyValuePair<string,string>("Faroe Islands", "Faroe Islands"));
            countries.Add(new KeyValuePair<string,string>("Fiji", "Fiji"));
            countries.Add(new KeyValuePair<string,string>("Finland", "Finland"));
            countries.Add(new KeyValuePair<string,string>("France", "France"));
            countries.Add(new KeyValuePair<string,string>("French Guiana", "French Guiana"));
            countries.Add(new KeyValuePair<string,string>("French Polynesia", "French Polynesia"));
            countries.Add(new KeyValuePair<string,string>("French Southern Territories", "French Southern Territories"));
            countries.Add(new KeyValuePair<string,string>("Gabon", "Gabon"));
            countries.Add(new KeyValuePair<string,string>("Gambia", "Gambia"));
            countries.Add(new KeyValuePair<string,string>("Germany", "Germany"));
            countries.Add(new KeyValuePair<string,string>("Ghana", "Ghana"));
            countries.Add(new KeyValuePair<string,string>("Gibraltar", "Gibraltar"));
            countries.Add(new KeyValuePair<string,string>("Great Britain", "Great Britain"));
            countries.Add(new KeyValuePair<string,string>("Greece", "Greece"));
            countries.Add(new KeyValuePair<string,string>("Greenland", "Greenland"));
            countries.Add(new KeyValuePair<string,string>("Grenada", "Grenada"));
            countries.Add(new KeyValuePair<string,string>("Guadeloupe", "Guadeloupe"));
            countries.Add(new KeyValuePair<string,string>("Guam", "Guam"));
            countries.Add(new KeyValuePair<string,string>("Guatemala", "Guatemala"));
            countries.Add(new KeyValuePair<string,string>("Guernsey", "Guernsey"));
            countries.Add(new KeyValuePair<string,string>("Guinea", "Guinea"));
            countries.Add(new KeyValuePair<string,string>("Guinea-Bissau", "Guinea-Bissau"));
            countries.Add(new KeyValuePair<string,string>("Guyana", "Guyana"));
            countries.Add(new KeyValuePair<string,string>("Haiti", "Haiti"));
            countries.Add(new KeyValuePair<string,string>("Heard Island and McDonald Islands", "Heard Island and McDonald Islands"));
            countries.Add(new KeyValuePair<string,string>("Holy See (Vatican City State)", "Holy See (Vatican City State)"));
            countries.Add(new KeyValuePair<string,string>("Honduras", "Honduras"));
            countries.Add(new KeyValuePair<string,string>("Hong Kong", "Hong Kong"));
            countries.Add(new KeyValuePair<string,string>("Hungary", "Hungary"));
            countries.Add(new KeyValuePair<string,string>("Iceland", "Iceland"));
            countries.Add(new KeyValuePair<string,string>("India", "India"));
            countries.Add(new KeyValuePair<string,string>("Indonesia", "Indonesia"));
            countries.Add(new KeyValuePair<string,string>("Ireland", "Ireland"));
            countries.Add(new KeyValuePair<string,string>("Isle of Man", "Isle of Man"));
            countries.Add(new KeyValuePair<string,string>("Israel", "Israel"));
            countries.Add(new KeyValuePair<string,string>("Italy", "Italy"));
            countries.Add(new KeyValuePair<string,string>("Jamaica", "Jamaica"));
            countries.Add(new KeyValuePair<string,string>("Japan", "Japan"));
            countries.Add(new KeyValuePair<string,string>("Jersey", "Jersey"));
            countries.Add(new KeyValuePair<string,string>("Kenya", "Kenya"));
            countries.Add(new KeyValuePair<string,string>("Kiribati", "Kiribati"));
            countries.Add(new KeyValuePair<string,string>("Korea, Republic of", "Korea, Republic of"));
            countries.Add(new KeyValuePair<string,string>("Kosovo", "Kosovo"));
            countries.Add(new KeyValuePair<string,string>("Kuwait", "Kuwait"));
            countries.Add(new KeyValuePair<string,string>("Latvia", "Latvia"));
            countries.Add(new KeyValuePair<string,string>("Lebanon", "Lebanon"));
            countries.Add(new KeyValuePair<string,string>("Lesotho", "Lesotho"));
            countries.Add(new KeyValuePair<string,string>("Liberia", "Liberia"));
            countries.Add(new KeyValuePair<string,string>("Liechtenstein", "Liechtenstein"));
            countries.Add(new KeyValuePair<string,string>("Lithuania", "Lithuania"));
            countries.Add(new KeyValuePair<string,string>("Luxembourg", "Luxembourg"));
            countries.Add(new KeyValuePair<string,string>("Macau", "Macau"));
            countries.Add(new KeyValuePair<string,string>("Macedonia", "Macedonia"));
            countries.Add(new KeyValuePair<string,string>("Madagascar", "Madagascar"));
            countries.Add(new KeyValuePair<string,string>("Malawi", "Malawi"));
            countries.Add(new KeyValuePair<string,string>("Malaysia", "Malaysia"));
            countries.Add(new KeyValuePair<string,string>("Maldives", "Maldives"));
            countries.Add(new KeyValuePair<string,string>("Mali", "Mali"));
            countries.Add(new KeyValuePair<string,string>("Malta", "Malta"));
            countries.Add(new KeyValuePair<string,string>("Marshall Islands", "Marshall Islands"));
            countries.Add(new KeyValuePair<string,string>("Martinique", "Martinique"));
            countries.Add(new KeyValuePair<string,string>("Mauritania", "Mauritania"));
            countries.Add(new KeyValuePair<string,string>("Mauritius", "Mauritius"));
            countries.Add(new KeyValuePair<string,string>("Mayotte", "Mayotte"));
            countries.Add(new KeyValuePair<string,string>("Mexico", "Mexico"));
            countries.Add(new KeyValuePair<string,string>("Micronesia, Federated States of", "Micronesia, Federated States of"));
            countries.Add(new KeyValuePair<string,string>("Monaco", "Monaco"));
            countries.Add(new KeyValuePair<string,string>("Montenegro", "Montenegro"));
            countries.Add(new KeyValuePair<string,string>("Montserrat", "Montserrat"));
            countries.Add(new KeyValuePair<string,string>("Morocco", "Morocco"));
            countries.Add(new KeyValuePair<string,string>("Mozambique", "Mozambique"));
            countries.Add(new KeyValuePair<string,string>("Namibia", "Namibia"));
            countries.Add(new KeyValuePair<string,string>("Nauru", "Nauru"));
            countries.Add(new KeyValuePair<string,string>("Nepal", "Nepal"));
            countries.Add(new KeyValuePair<string,string>("Netherlands Antilles", "Netherlands Antilles"));
            countries.Add(new KeyValuePair<string,string>("New Caledonia", "New Caledonia"));
            countries.Add(new KeyValuePair<string,string>("New Zealand", "New Zealand"));
            countries.Add(new KeyValuePair<string,string>("Nicaragua", "Nicaragua"));
            countries.Add(new KeyValuePair<string,string>("Niger", "Niger"));
            countries.Add(new KeyValuePair<string,string>("Nigeria", "Nigeria"));
            countries.Add(new KeyValuePair<string,string>("Niue", "Niue"));
            countries.Add(new KeyValuePair<string,string>("Norfolk Island", "Norfolk Island"));
            countries.Add(new KeyValuePair<string,string>("Northern Ireland", "Northern Ireland"));
            countries.Add(new KeyValuePair<string,string>("Northern Mariana Islands", "Northern Mariana Islands"));
            countries.Add(new KeyValuePair<string,string>("Norway", "Norway"));
            countries.Add(new KeyValuePair<string,string>("Oman", "Oman"));
            countries.Add(new KeyValuePair<string,string>("Palau", "Palau"));
            countries.Add(new KeyValuePair<string,string>("Panama", "Panama"));
            countries.Add(new KeyValuePair<string,string>("Papua New Guinea", "Papua New Guinea"));
            countries.Add(new KeyValuePair<string,string>("Paraguay", "Paraguay"));
            countries.Add(new KeyValuePair<string,string>("Peru", "Peru"));
            countries.Add(new KeyValuePair<string,string>("Philippines", "Philippines"));
            countries.Add(new KeyValuePair<string,string>("Pitcairn", "Pitcairn"));
            countries.Add(new KeyValuePair<string,string>("Poland", "Poland"));
            countries.Add(new KeyValuePair<string,string>("Portugal", "Portugal"));
            countries.Add(new KeyValuePair<string,string>("Puerto Rico", "Puerto Rico"));
            countries.Add(new KeyValuePair<string,string>("Qatar", "Qatar"));
            countries.Add(new KeyValuePair<string,string>("Reunion", "Reunion"));
            countries.Add(new KeyValuePair<string,string>("Romania", "Romania"));
            countries.Add(new KeyValuePair<string,string>("Rwanda", "Rwanda"));
            countries.Add(new KeyValuePair<string,string>("Saint Helena", "Saint Helena"));
            countries.Add(new KeyValuePair<string,string>("Saint Kitts and Nevis", "Saint Kitts and Nevis"));
            countries.Add(new KeyValuePair<string,string>("Saint Lucia", "Saint Lucia"));
            countries.Add(new KeyValuePair<string,string>("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"));
            countries.Add(new KeyValuePair<string,string>("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"));
            countries.Add(new KeyValuePair<string,string>("Samoa", "Samoa"));
            countries.Add(new KeyValuePair<string,string>("San Marino", "San Marino"));
            countries.Add(new KeyValuePair<string,string>("Sao Tome and Principe", "Sao Tome and Principe"));
            countries.Add(new KeyValuePair<string,string>("Saudi Arabia", "Saudi Arabia"));
            countries.Add(new KeyValuePair<string,string>("Scotland", "Scotland"));
            countries.Add(new KeyValuePair<string,string>("Senegal", "Senegal"));
            countries.Add(new KeyValuePair<string,string>("Serbia", "Serbia"));
            countries.Add(new KeyValuePair<string,string>("Seychelles", "Seychelles"));
            countries.Add(new KeyValuePair<string,string>("Sierra Leone", "Sierra Leone"));
            countries.Add(new KeyValuePair<string,string>("Singapore", "Singapore"));
            countries.Add(new KeyValuePair<string,string>("Slovakia", "Slovakia"));
            countries.Add(new KeyValuePair<string,string>("Slovenia", "Slovenia"));
            countries.Add(new KeyValuePair<string,string>("Solomon Islands", "Solomon Islands"));
            countries.Add(new KeyValuePair<string,string>("Somalia", "Somalia"));
            countries.Add(new KeyValuePair<string,string>("South Africa", "South Africa"));
            countries.Add(new KeyValuePair<string,string>("South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands"));
            countries.Add(new KeyValuePair<string,string>("Spain", "Spain"));
            countries.Add(new KeyValuePair<string,string>("Sri Lanka", "Sri Lanka"));
            countries.Add(new KeyValuePair<string,string>("Suriname", "Suriname"));
            countries.Add(new KeyValuePair<string,string>("Svalbard", "Svalbard"));
            countries.Add(new KeyValuePair<string,string>("Swaziland", "Swaziland"));
            countries.Add(new KeyValuePair<string,string>("Sweden", "Sweden"));
            countries.Add(new KeyValuePair<string,string>("Switzerland", "Switzerland"));
            countries.Add(new KeyValuePair<string,string>("Taiwan", "Taiwan"));
            countries.Add(new KeyValuePair<string,string>("Tanzania", "Tanzania"));
            countries.Add(new KeyValuePair<string,string>("Thailand", "Thailand"));
            countries.Add(new KeyValuePair<string,string>("Timor-Leste", "Timor-Leste"));
            countries.Add(new KeyValuePair<string,string>("Togo", "Togo"));
            countries.Add(new KeyValuePair<string,string>("Tokelau", "Tokelau"));
            countries.Add(new KeyValuePair<string,string>("Tonga", "Tonga"));
            countries.Add(new KeyValuePair<string,string>("Trinidad and Tobago", "Trinidad and Tobago"));
            countries.Add(new KeyValuePair<string,string>("Tunisia", "Tunisia"));
            countries.Add(new KeyValuePair<string,string>("Turkey", "Turkey"));
            countries.Add(new KeyValuePair<string,string>("Turks and Caicos Islands", "Turks and Caicos Islands"));
            countries.Add(new KeyValuePair<string,string>("Tuvalu", "Tuvalu"));
            countries.Add(new KeyValuePair<string,string>("Uganda", "Uganda"));
            countries.Add(new KeyValuePair<string,string>("United States Minor Outlying Islands", "United States Minor Outlying Islands"));
            countries.Add(new KeyValuePair<string,string>("Uruguay", "Uruguay"));
            countries.Add(new KeyValuePair<string,string>("Vanuatu", "Vanuatu"));
            countries.Add(new KeyValuePair<string,string>("Venezuela", "Venezuela"));
            countries.Add(new KeyValuePair<string,string>("Virgin Islands, British", "Virgin Islands, British"));
            countries.Add(new KeyValuePair<string,string>("Virgin Islands, U.S.", "Virgin Islands, U.S."));
            countries.Add(new KeyValuePair<string,string>("Wallis and Futuna", "Wallis and Futuna"));
            countries.Add(new KeyValuePair<string,string>("Western Sahara", "Western Sahara"));
            countries.Add(new KeyValuePair<string,string>("Yemen", "Yemen"));
            countries.Add(new KeyValuePair<string,string>("Zambia", "Zambia"));
            countries.Add(new KeyValuePair<string,string>("Zimbabwe", "Zimbabwe"));

            return countries;
        }
    }
}
