//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedySpots.Controls {
    
    
    public partial class SpeedySpotsTabs {
        
        /// <summary>
        /// m_oRequestDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpeedySpots.Controls.RequestDetails m_oRequestDetails;
        
        /// <summary>
        /// m_oRequestNotes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpeedySpots.Controls.RequestNotes m_oRequestNotes;
        
        /// <summary>
        /// m_oJobDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SpeedySpots.Controls.JobDetails m_oJobDetails;
    }
}
