CREATE TABLE [dbo].[IASpotFee]
(
[IASpotFeeID] [int] NOT NULL IDENTITY(1, 1),
[IASpotID] [int] NOT NULL CONSTRAINT [DF_IASpotFee_IASpotID] DEFAULT ((0)),
[IASpotFeeTypeID] [int] NOT NULL CONSTRAINT [DF_IASpotFee_IASpotFeeTypeID] DEFAULT ((0)),
[Fee] [money] NOT NULL CONSTRAINT [DF_IASpotFee_Fee] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IASpotFee] ADD CONSTRAINT [PK_IASpotFee] PRIMARY KEY CLUSTERED  ([IASpotFeeID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IASpotFee] ADD CONSTRAINT [FK_IASpotFee_IASpotFeeType] FOREIGN KEY ([IASpotFeeTypeID]) REFERENCES [dbo].[IASpotFeeType] ([IASpotFeeTypeID])
GO
ALTER TABLE [dbo].[IASpotFee] ADD CONSTRAINT [FK_IASpotFee_IASpot] FOREIGN KEY ([IASpotID]) REFERENCES [dbo].[IASpot] ([IASpotID]) ON DELETE CASCADE
GO
