CREATE TABLE [dbo].[IASpotType]
(
[IASpotTypeID] [int] NOT NULL,
[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_IASpotType_Name] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IASpotType] ADD CONSTRAINT [PK_IASpotType] PRIMARY KEY CLUSTERED  ([IASpotTypeID]) ON [PRIMARY]
GO
