//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedySpots.InetActive {
    
    
    public partial class MemberProtectParams {
        
        /// <summary>
        /// m_txtTimespanBeforePasswordsExpire control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtTimespanBeforePasswordsExpire;
        
        /// <summary>
        /// m_txtTimespanBeforePasswordsExpireToNotifyUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtTimespanBeforePasswordsExpireToNotifyUsers;
        
        /// <summary>
        /// m_txtTimespanBeforeTempPasswordsExpire control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtTimespanBeforeTempPasswordsExpire;
        
        /// <summary>
        /// m_txtTimespanSinceLastLoginBeforeLockout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtTimespanSinceLastLoginBeforeLockout;
        
        /// <summary>
        /// m_txtTimespanToKeepLogs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtTimespanToKeepLogs;
        
        /// <summary>
        /// m_txtMaxPasswordHistoryCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtMaxPasswordHistoryCount;
        
        /// <summary>
        /// m_txtMaxFailedLoginAttemptsBeforeLockout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtMaxFailedLoginAttemptsBeforeLockout;
        
        /// <summary>
        /// m_txtRBASystemTrackCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadNumericTextBox m_txtRBASystemTrackCount;
        
        /// <summary>
        /// m_btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton m_btnSave;
    }
}
